#define STEPS_RPM_SLOW 10
#define STEPS_RPM_NORMAL 15
#define STEPS_RPM_FAST 20
#define STEPS_DELAY_SLOW 3
#define STEPS_DELAY_NORMAL 6
#define STEPS_DELAY_FAST 9
#define STEPS_REVOLUTION 2038

#define LOOP_DELAY 1000

#define SERVO_PIN 6